### ISSUE TITLE
Revise Database Schema

### ISSUE THREAD

**Issue by blchelle** [blchelle/collabogreat#45]
## Description
Update the MongoDB database schema to create an easily understandable system

### Sub-Tasks
- [x] Come up with a list of entities
- [x] Come up with a list of responsibilities for all of the entities
- [x] Come up with an informal set of collections
- [x] Formalize the collection set
- [x] Document how we will query for the most common use cases
    * How does a user sign up?
    * How do we add a user to a project?
    * How do we create a ticket?
    * How do we create a project?
    * How do we delete a project?
    * How do we delete a ticket?
- [x] Create a wiki page documenting the design decisions

### Deliverables
The final deliverable for this issue is the presence of a wiki page with the following sections
1. Entities & Responsibilities
2. Collections
3.  Common Use Case Procedures
